version: '3.5'
services:
  drachtio:
    image: registry.gitlab.com/avaamo/sip-server:drachtio-server-tlscert-2024
    hostname: drachtio-server
    container_name: drachtio-server
    network_mode: host
    restart: always
    command: drachtio --contact "sip:*:5060;transport=udp,tcp"  --external-ip 34.211.200.74 --contact "sips:*:5061;transport=tls"  --external-ip 34.211.200.74 --key-file "/sip-key.pem" --chain-file "/sip-chain.pem" --cert-file "/sip-cert.pem" --dh-param "sip-dhparam.pem" --contact "sip:*:4432;transport=ws"  --loglevel info --sofia-loglevel 1
    ports:
      - "5060:5060"
      - "5061:5061"
    volumes:
      - ./keys:/usr/local/keys
      - /home/$USER/volume/logs/drachtio-server:/var/log/drachtio

  freeswitch:
    image: registry.gitlab.com/avaamo/sip-server:drachtio-freeswitch-mrf
    hostname: drachtio-freeswitch-mrf
    container_name: drachtio-freeswitch-mrf
    command: freeswitch --sip-port 5080 --rtp-range-start 30000 --rtp-range-end 39999
    network_mode: host
    restart: always
    ports:
      - "8021:8021"
      - "5080:5080"
      - "30000-39999/udp"
    volumes:
      - /home/$USER/volume/logs/drachtio-freeswitch:/usr/local/freeswitch/log

  siprec-recording:
    container_name: drachtio-siprec
    build:
      context: /home/dheeraj/drachtio_siprec/drachtio-siprec-recording-server
      dockerfile: /home/dheeraj/drachtio_siprec/drachtio-siprec-recording-server/Dockerfile
    network_mode: "host"
    command: "node app"
    volumes:
      - ./tmp/rtpengine:/tmp/rtp1
